"""add explicit task_date and session_date

Revision ID: 0507f4c27e07
Revises: 3112481f2910
Create Date: 2026-01-16 18:23:53.784272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0507f4c27e07'
down_revision: Union[str, Sequence[str], None] = '3112481f2910'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('focus_sessions', sa.Column('session_date', sa.Date(), nullable=False))
    op.add_column('tasks', sa.Column('task_date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'task_date')
    op.drop_column('focus_sessions', 'session_date')
    # ### end Alembic commands ###
